# This module defines the collections of attributes available for event
# callbacks.
# 
module RubyAwCallbackAttributes
  
  def self.callback_attributes_for(callback, *attributes)
    @@attrs_available_to ||= {}
    @@attrs_available_to[callback] = attributes
  end
  
  callback_attributes_for :AW_CALLBACK_ADDRESS, :AW_AVATAR_SESSION, :AW_AVATAR_ADDRESS
  callback_attributes_for :AW_CALLBACK_AVATAR_LOCATION, :AW_AVATAR_SESSION,
    :AW_AVATAR_NAME, :AW_AVATAR_X, :AW_AVATAR_Y, :AW_AVATAR_Z, :AW_AVATAR_YAW, :AW_AVATAR_PITCH,
    :AW_AVATAR_TYPE, :AW_AVATAR_GESTURE, :AW_AVATAR_STATE, :AW_AVATAR_VERSION,
    :AW_AVATAR_CITIZEN, :AW_AVATAR_PRIVILEGE, :AW_AVATAR_LOCK, :AW_PLUGIN_STRING
  callback_attributes_for :AW_CALLBACK_ADMIN_WORLD_RESULT,
    :AW_SERVER_ID, :AW_SERVER_INSTANCE, :AW_SERVER_NAME
  
  callback_attributes_for :AW_CALLBACK_ADMIN_WORLD_LIST, :AW_SERVER_ID
  callback_attributes_for :AW_CALLBACK_ADMIN, :AW_SERVER_BUILD, :AW_WORLD_BUILD_NUMBER
  
  callback_attributes_for :AW_CALLBACK_CELL_RESULT, :AW_CELL_ITERATOR
  callback_attributes_for :AW_CALLBACK_CITIZEN_RESULT, :AW_CITIZEN_NUMBER
  callback_attributes_for :AW_CALLBACK_CITIZEN_ATTRIBUTES,
    :AW_CITIZEN_NUMBER, :AW_CITIZEN_NAME, :AW_CITIZEN_PASSWORD,
    :AW_CITIZEN_EMAIL, :AW_CITIZEN_ENABLED, :AW_CITIZEN_BETA,
    :AW_CITIZEN_TRIAL, :AW_CITIZEN_CAV_ENABLED, :AW_CITIZEN_PAV_ENABLED,
    :AW_CITIZEN_BOT_LIMIT, :AW_CITIZEN_COMMENT, :AW_CITIZEN_EXPIRATION_TIME,
    :AW_CITIZEN_IMMIGRATION_TIME, :AW_CITIZEN_LAST_LOGIN,
    :AW_CITIZEN_PRIVILEGE_PASSWORD, :AW_CITIZEN_PRIVACY,
    :AW_CITIZEN_TOTAL_TIME, :AW_CITIZEN_URL
  
  callback_attributes_for :AW_CALLBACK_ENTER, :AW_WORLD_NAME
  
  callback_attributes_for :AW_CALLBACK_HUD_RESULT, :AW_HUD_ELEMENT_SESSION, :AW_HUD_ELEMENT_ID
  
  callback_attributes_for :AW_CALLBACK_LICENSE_ATTRIBUTES,
    :AW_LICENSE_PASSWORD, :AW_LICENSE_USERS, :AW_LICENSE_RANGE,
    :AW_LICENSE_EMAIL, :AW_LICENSE_COMMENT, :AW_LICENSE_CREATION_TIME,
    :AW_LICENSE_EXPIRATION_TIME, :AW_LICENSE_LAST_START,
    :AW_LICENSE_LAST_ADDRESS, :AW_LICENSE_HIDDEN, :AW_LICENSE_ALLOW_TOURISTS,
    :AW_LICENSE_VOIP, :AW_LICENSE_PLUGINS
  
  callback_attributes_for :AW_CALLBACK_LOGIN, :AW_CITIZEN_BETA,
    :AW_CITIZEN_CAV_ENABLED, :AW_CITIZEN_NAME, :AW_CITIZEN_NUMBER,
    :AW_CITIZEN_PAV_ENABLED, :AW_CITIZEN_TIME_LEFT, :AW_LOGIN_PRIVILEGE_NAME
    
  callback_attributes_for :AW_CALLBACK_OBJECT_RESULT, :AW_OBJECT_NUMBER,
    :AW_OBJECT_ID, :AW_OBJECT_CALLBACK_REFERENCE, :AW_CELL_X, :AW_CELL_Z
  callback_attributes_for :AW_CALLBACK_OBJECT_QUERY, 
    :AW_OBJECT_TYPE, :AW_OBJECT_ID, :AW_OBJECT_NUMBER, :AW_OBJECT_OWNER,
    :AW_OBJECT_BUILD_TIMESTAMP, :AW_OBJECT_X, :AW_OBJECT_Y, :AW_OBJECT_Z,
    :AW_OBJECT_YAW, :AW_OBJECT_TILT, :AW_OBJECT_ROLL, :AW_OBJECT_MODEL,
    :AW_OBJECT_DESCRIPTION, :AW_OBJECT_ACTION, :AW_OBJECT_DATA
  
  callback_attributes_for :AW_CALLBACK_QUERY, :AW_QUERY_COMPLETE
  callback_attributes_for :AW_CALLBACK_TERRAIN_NEXT_RESULT, :AW_TERRAIN_COMPLETE
  callback_attributes_for :AW_CALLBACK_TERRAIN_SET_RESULT, :AW_TERRAIN_X, :AW_TERRAIN_Z
  
  callback_attributes_for :AW_CALLBACK_USER_LIST, :AW_USERLIST_MORE
  callback_attributes_for :AW_CALLBACK_UNIVERSE_EJECTION, :AW_EJECTION_ADDRESS,
    :AW_EJECTION_CREATION_TIME, :AW_EJECTION_EXPIRATION_TIME, :AW_EJECTION_COMMENT
    
  callback_attributes_for :AW_CALLBACK_WORLD_LIST, :AW_WORLDLIST_MORE
  callback_attributes_for :AW_CALLBACK_WORLD_EJECTION, :AW_EJECTION_TYPE,
    :AW_EJECTION_ADDRESS, :AW_EJECTION_CREATION_TIME, :AW_EJECTION_EXPIRATION_TIME, 
    :AW_EJECTION_COMMENT
  callback_attributes_for :AW_CALLBACK_WORLD_INSTANCE, :AW_AVATAR_CITIZEN, :AW_AVATAR_WORLD_INSTANCE
  
end
